export const yakuDefinitions = [
  {
    id: "riichi",
    name: "리치",
    hanClosed: 1,
    hanOpen: null,
    score: 10,
    implemented: true,
    text: "한 장만 교체하면 완성 가능한 상태에서 선언합니다. 선언 뒤에는 정해진 패만 자동으로 교체하며, 리치만으로도 화료 조건을 채울 수 있습니다.",
    exampleTiles: "123m 456m 789p 123s 55m",
  },
  {
    id: "rinshanKaiho",
    name: "영상개화",
    hanClosed: 1,
    hanOpen: 1,
    score: 10,
    implemented: true,
    text: "깡을 선언한 뒤 받은 영상패로 손패가 완성되면 붙습니다.",
    example: "깡 뒤 영상패로 완성",
  },
  {
    id: "sankantsu",
    name: "삼깡쯔",
    hanClosed: 2,
    hanOpen: 2,
    score: 30,
    implemented: true,
    text: "한 손패에서 깡을 3번 선언하면 붙습니다.",
    example: "깡 3개",
  },
  {
    id: "sukantsu",
    name: "사깡쯔",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "한 손패에서 깡을 4번 선언하면 성립하는 역만입니다.",
    example: "깡 4개",
  },
  {
    id: "menzenTsumo",
    name: "멘젠쯔모",
    hanClosed: 1,
    hanOpen: null,
    score: 10,
    implemented: false,
    text: "남의 패를 가져오지 않고 스스로 뽑은 패로 완성하면 붙습니다. 현재는 별도 쯔모 상태가 없어 판정하지 않습니다.",
    example: "마지막 패를 직접 뽑아 완성",
  },
  {
    id: "tanyao",
    name: "탕야오",
    hanClosed: 1,
    hanOpen: 1,
    score: 10,
    implemented: true,
    text: "1, 9, 자패 없이 2부터 8까지의 숫자패만 사용합니다.",
    exampleTiles: "234m 234p 345s 678m 66p",
  },
  {
    id: "pinfu",
    name: "핑후",
    hanClosed: 1,
    hanOpen: null,
    score: 12,
    implemented: true,
    text: "모든 몸통이 슌쯔이고 머리가 점수패가 아닌 기본형입니다. 현재는 대기 형태를 단순화해 판정합니다.",
    exampleTiles: "123m 234p 345s 678m 55p",
  },
  {
    id: "yakuhai",
    name: "역패",
    hanClosed: 1,
    hanOpen: 1,
    score: 12,
    implemented: true,
    text: "백, 발, 중을 3장 모으면 붙습니다. 장풍과 자풍 판정은 이후 단계에서 확장합니다.",
    exampleTiles: "CCCz FFFz",
  },
  {
    id: "iipeko",
    name: "이페코",
    hanClosed: 1,
    hanOpen: null,
    score: 10,
    implemented: true,
    text: "같은 종류와 같은 숫자 시작의 슌쯔를 2개 만듭니다.",
    exampleTiles: "123m 123m 456p 789p 55s",
  },
  {
    id: "chiitoitsu",
    name: "칠대자",
    hanClosed: 2,
    hanOpen: null,
    score: 24,
    implemented: true,
    text: "같은 패 2장짜리 짝을 7개 만드는 특수 형태입니다.",
    exampleTiles: "11m 44m 22p 55p 33s 77s CCz",
  },
  {
    id: "toitoi",
    name: "또이또이",
    hanClosed: 2,
    hanOpen: 2,
    score: 30,
    implemented: true,
    text: "모든 몸통을 같은 패 3장으로 만듭니다.",
    exampleTiles: "111m 444p 555s CCCz 22p",
  },
  {
    id: "sanshokuDoujun",
    name: "삼색동순",
    hanClosed: 2,
    hanOpen: 1,
    score: 28,
    implemented: true,
    text: "만수, 통수, 삭수에 같은 숫자 연속 묶음을 하나씩 만듭니다.",
    exampleTiles: "234m 234p 234s 345s 66p",
  },
  {
    id: "ittsu",
    name: "일기통관",
    hanClosed: 2,
    hanOpen: 1,
    score: 28,
    implemented: true,
    text: "한 종류의 수패로 1-2-3, 4-5-6, 7-8-9를 모두 만듭니다.",
    exampleTiles: "123m 456m 789m 111p 99s",
  },
  {
    id: "sanshokuDouko",
    name: "삼색동각",
    hanClosed: 2,
    hanOpen: 2,
    score: 30,
    implemented: true,
    text: "만수, 통수, 삭수에 같은 숫자의 커쯔를 하나씩 만듭니다.",
    exampleTiles: "222m 222p 222s 345m 99p",
  },
  {
    id: "sananko",
    name: "삼암각",
    hanClosed: 2,
    hanOpen: 2,
    score: 30,
    implemented: true,
    text: "커쯔 3개를 만듭니다. 현재 버전에서는 론/쯔모와 후로 정보 없이 커쯔 개수로 단순 판정합니다.",
    exampleTiles: "111m 444p 555s 678m 22p",
  },
  {
    id: "shosangen",
    name: "소삼원",
    hanClosed: 2,
    hanOpen: 2,
    score: 32,
    implemented: true,
    text: "백, 발, 중 중 2개를 커쯔로 만들고 나머지 하나를 머리로 둡니다.",
    exampleTiles: "PPPz FFFz CCz 123m 123p",
  },
  {
    id: "honroto",
    name: "혼노두",
    hanClosed: 2,
    hanOpen: 2,
    score: 36,
    implemented: true,
    text: "모든 패를 1, 9 또는 자패로만 구성합니다.",
    exampleTiles: "11m 99m 11p 99p 11s 99s EEz",
  },
  {
    id: "chanta",
    name: "찬타",
    hanClosed: 2,
    hanOpen: 1,
    score: 24,
    implemented: true,
    text: "모든 몸통과 머리에 요구패가 포함되고, 슌쯔가 1개 이상 있어야 합니다.",
    exampleTiles: "123m 789m EEEz 999p SSz",
  },
  {
    id: "junchan",
    name: "준찬타",
    hanClosed: 3,
    hanOpen: 2,
    score: 42,
    implemented: true,
    text: "모든 몸통과 머리에 끝패가 포함되고, 자패 없이 슌쯔가 1개 이상 있어야 합니다.",
    exampleTiles: "123m 789m 111p 999p 99s",
  },
  {
    id: "ryanpeko",
    name: "량페코",
    hanClosed: 3,
    hanOpen: null,
    score: 48,
    implemented: true,
    text: "서로 다른 이페코 2개를 동시에 만듭니다.",
    exampleTiles: "223344m 556677p 88s",
  },
  {
    id: "honitsu",
    name: "혼일색",
    hanClosed: 3,
    hanOpen: 2,
    score: 42,
    implemented: true,
    text: "한 종류의 숫자패와 자패만 사용합니다.",
    exampleTiles: "123m 456m 789m CCCz EEz",
  },
  {
    id: "chinitsu",
    name: "청일색",
    hanClosed: 6,
    hanOpen: 5,
    score: 80,
    implemented: true,
    text: "한 종류의 숫자패만 사용합니다. 자패가 들어가면 성립하지 않습니다.",
    exampleTiles: "123p 456p 789p 234p 55p",
  },
  {
    id: "kokushiMusou",
    name: "국사무쌍",
    hanClosed: 13,
    hanOpen: null,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "13종 요구패를 모두 모으고 그중 하나를 한 쌍으로 만듭니다.",
    exampleTiles: "19m 19p 19s ESWNPFCz 1m",
  },
  {
    id: "suanko",
    name: "사암각",
    hanClosed: 13,
    hanOpen: null,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "커쯔 4개를 만듭니다. 현재 버전에서는 후로/론 정보 없이 커쯔 4개로 단순 판정합니다.",
    exampleTiles: "111m 222p 333s CCCz 99m",
  },
  {
    id: "daisangen",
    name: "대삼원",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "백, 발, 중을 모두 커쯔로 만듭니다.",
    exampleTiles: "PPPz FFFz CCCz 123m 99s",
  },
  {
    id: "shosushi",
    name: "소사희",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "동, 남, 서, 북 중 3개를 커쯔로 만들고 나머지 하나를 머리로 둡니다.",
    exampleTiles: "EEEz SSSz WWWz NNz 123m",
  },
  {
    id: "daisushi",
    name: "대사희",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "동, 남, 서, 북을 모두 커쯔로 만듭니다.",
    exampleTiles: "EEEz SSSz WWWz NNNz 11m",
  },
  {
    id: "tsuuiiso",
    name: "자일색",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "모든 패를 자패로만 구성합니다.",
    exampleTiles: "EEEz SSSz PPPz CCCz FFz",
  },
  {
    id: "chinroto",
    name: "청노두",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "모든 패를 1과 9 수패로만 구성합니다.",
    exampleTiles: "111m 999m 111p 999p 11s",
  },
  {
    id: "ryuiso",
    name: "녹일색",
    hanClosed: 13,
    hanOpen: 13,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "삭수 2, 3, 4, 6, 8과 발만 사용합니다.",
    exampleTiles: "222s 333s 444s 666s FFz",
  },
  {
    id: "churenPoto",
    name: "구련보등",
    hanClosed: 13,
    hanOpen: null,
    score: 160,
    yakuman: true,
    implemented: true,
    text: "한 종류의 수패로 1112345678999 형태와 같은 패 추가 1장을 만듭니다.",
    exampleTiles: "11123456789999m",
  },
];

export const yakuById = new Map(yakuDefinitions.map((item) => [item.id, item]));
export const yakuReference = yakuDefinitions
  .filter((item) => item.implemented)
  .sort(compareYakuReference)
  .map((item) => ({
    name: item.name,
    han: formatHan(item),
    score: item.score,
    text: item.text,
    exampleTiles: item.exampleTiles,
  }));

export function createYaku(id) {
  const definition = yakuById.get(id);
  if (!definition) throw new Error(`Unknown yaku id: ${id}`);
  return {
    id: definition.id,
    name: definition.name,
    han: definition.hanClosed,
    score: definition.score,
    yakuman: Boolean(definition.yakuman),
  };
}

function formatHan(item) {
  if (item.yakuman) return "역만";
  if (item.hanClosed === item.hanOpen || item.hanOpen == null) return `${item.hanClosed}판`;
  return `멘젠 ${item.hanClosed}판 / 부로 ${item.hanOpen}판`;
}

function compareYakuReference(a, b) {
  return getSortHan(a) - getSortHan(b)
    || a.score - b.score
    || a.name.localeCompare(b.name, "ko");
}

function getSortHan(item) {
  if (item.yakuman) return 13;
  return Math.min(item.hanClosed, item.hanOpen ?? item.hanClosed);
}
